name: Cypress CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client/
          start: npm run serve
          build: npx cypress info
          wait-on: 'http://localhost:8080'

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: client/cypress/results

      - name: Report coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: client/coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2



